package main

import (
	"bytes"
	"encoding/json"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

func buildCLI(t *testing.T) string {
	t.Helper()
	binary := filepath.Join(t.TempDir(), "budget")
	if runtime.GOOS == "windows" {
		binary += ".exe"
	}
	if output, err := exec.Command("go", "build", "-o", binary, ".").CombinedOutput(); err != nil {
		t.Fatalf("build: %v\n%s", err, output)
	}
	return binary
}

func TestHelpExitStatus(t *testing.T) {
	binary := buildCLI(t)
	for _, arg := range []string{"-h", "-help"} {
		cmd := exec.Command(binary, arg)
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		output, err := cmd.Output()
		if err != nil || stderr.Len() != 0 || !bytes.Contains(output, []byte("Usage of budget:")) {
			t.Fatalf("%s: err=%v stderr=%q stdout=%q", arg, err, &stderr, output)
		}
	}
	if err := exec.Command(binary, "-unknown").Run(); err == nil {
		t.Fatal("unknown flag exited successfully")
	}
}

func TestCLILineDirectives(t *testing.T) {
	dir := t.TempDir()
	source := "package example\n//line other.go:1\nfunc f() {\n println(1)\n//line other.go:1\n println(2)\n}\n"
	if err := os.WriteFile(filepath.Join(dir, "example.go"), []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if err := run([]string{"-json", dir}, &out); err != nil {
		t.Fatal(err)
	}
	var got measurements
	if err := json.Unmarshal(out.Bytes(), &got); err != nil {
		t.Fatal(err)
	}
	if got.LOC != 5 || len(got.Functions) != 1 {
		t.Fatalf("measurements: %+v", got)
	}
	f := got.Functions[0]
	if f.LOC != 4 || f.Line != 3 || f.File != "example.go" {
		t.Fatalf("function: %+v", f)
	}
}

func TestCLI(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"main.go": `package example
// Example command callback.
var run = func(ok bool) {
	if ok && ready() { work() }
}
func outer() {
	// A nested callback gets its own budget.
	fn := func() {
		for ready() { work() }
	}
	fn()
}
`,
		"main_test.go":       "package example\nfunc TestExample() {}\n",
		"generated.go":       "// Code generated by example. DO NOT EDIT.\npackage example\nfunc Generated() {}\n",
		"testdata/broken.go": "this is not Go",
		"vendor/broken.go":   "this is not Go",
		".hidden/broken.go":  "this is not Go",
	}
	for name, source := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	var output bytes.Buffer
	if err := run([]string{"-json", dir}, &output); err != nil {
		t.Fatal(err)
	}
	var data measurements
	if err := json.Unmarshal(output.Bytes(), &data); err != nil {
		t.Fatal(err)
	}
	got := data.Functions
	if len(got) != 3 {
		t.Fatalf("functions = %v", got)
	}
	for i, want := range []struct{ line, loc, cc int }{{3, 5, 3}, {6, 4, 1}, {8, 5, 2}} {
		if got[i].Line != want.line || got[i].LOC != want.loc || got[i].CC != want.cc {
			t.Errorf("function %d = %+v, want %+v", i, got[i], want)
		}
	}
	output.Reset()
	if err := run([]string{"-tests", "-at", "1", "-power", "0", dir}, &output); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(output.String(), "4 functions;") || !strings.Contains(output.String(), "Top violations for p=0:") || !strings.Contains(output.String(), "main.go:3") {
		t.Fatal(output.String())
	}
}

func TestBranchCounting(t *testing.T) {
	source := `package example
func branches(x int, ch chan int) {
	if x > 0 || x < -1 { }
	for i := 0; i < x; i++ { }
	for range ch { }
	switch x { case 1, 2: case 3: default: }
	select { case <-ch: default: }
	switch any(x).(type) { case int: default: }
}
`
	got, err := measure("example.go", []byte(source))
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Functions) != 1 || got.Functions[0].CC != 9 {
		t.Fatalf("measurements = %+v", got)
	}
}

func TestFormattingAndComments(t *testing.T) {
	plain := "package example\nfunc f(x bool) { if x { println(1) } }\n"
	commented := "package example\n// doc\nfunc f(x bool) {\n\n/* multi\nline */ if x { // inline\nprintln(1)\n}\n}\n"
	a, err := measure("a.go", []byte(plain))
	if err != nil {
		t.Fatal(err)
	}
	b, err := measure("b.go", []byte(commented))
	if err != nil {
		t.Fatal(err)
	}
	if a.LOC != b.LOC || a.Functions[0].CC != b.Functions[0].CC {
		t.Fatalf("formatting changed metrics: %+v vs %+v", a, b)
	}
}

func TestCurve(t *testing.T) {
	c := curve{1, 10, 40, 0.5}
	for loc, want := range map[int]float64{10: 5.5, 40: 10, 160: 19} {
		if math.Abs(c.ceiling(loc)-want) > 1e-10 {
			t.Errorf("ceiling(%d) = %g, want %g", loc, c.ceiling(loc), want)
		}
	}
	for _, args := range [][]string{{"-power", "1"}, {"-power", "-1"}, {"-loc", "0"}, {"-at", "NaN"}, {"-base", "Inf"}, {"-top", "-1"}, {"-boolean", "-1"}, {"-nesting", "-1"}, {"-file-decisions", "-1"}} {
		if err := run(args, &bytes.Buffer{}); err == nil {
			t.Errorf("accepted %v", args)
		}
	}
}

func TestCLIReceiverNamesAndPositions(t *testing.T) {
	dir := t.TempDir()
	source := "package example\n\ntype Box[T any] struct { Value T }\n\nfunc (b *Box[T]) Get() T { return b.Value }\nfunc external()\n"
	if err := os.WriteFile(filepath.Join(dir, "box.go"), []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	var output bytes.Buffer
	if err := run([]string{"-json", dir}, &output); err != nil {
		t.Fatal(err)
	}
	var data measurements
	if err := json.Unmarshal(output.Bytes(), &data); err != nil {
		t.Fatal(err)
	}
	if len(data.Functions) != 1 {
		t.Fatalf("functions: %+v", data.Functions)
	}
	f := data.Functions[0]
	if f.Name != "(*Box[T]).Get" || f.Line != 5 || f.CC != 1 {
		t.Fatalf("function: %+v", f)
	}
}

func TestCLIFileErrors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "broken.go")
	if err := run([]string{path}, &bytes.Buffer{}); err == nil {
		t.Fatal("missing input was accepted")
	}
	if err := os.WriteFile(path, []byte("package example\nfunc broken("), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := run([]string{dir}, &bytes.Buffer{}); err == nil {
		t.Fatal("invalid Go was accepted")
	}
}

func TestCLIExclusionsAndRelativePaths(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "testdata"), 0o755); err != nil {
		t.Fatal(err)
	}
	for name, source := range map[string]string{
		"example.go":         "package example\nfunc f() {}\n",
		"testdata/broken.go": "invalid Go",
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	t.Chdir(filepath.Dir(dir))
	relative := filepath.Base(dir)
	var previous measurements
	for _, root := range []string{dir, relative} {
		var out bytes.Buffer
		if err := run([]string{"-json", "-exclude", "vendor, testdata, ,", root}, &out); err != nil {
			t.Fatal(err)
		}
		var got measurements
		if err := json.Unmarshal(out.Bytes(), &got); err != nil {
			t.Fatal(err)
		}
		if len(got.Files) != 1 || got.Files[0].Name != "example.go" {
			t.Fatalf("files: %+v", got.Files)
		}
		if got.Functions[0].File != "example.go" || got.Files[0].Package != ".:example" {
			t.Fatalf("measurements: %+v", got)
		}
		if previous.Files != nil && !reflect.DeepEqual(previous, got) {
			t.Fatal("root spelling changed JSON measurements")
		}
		previous = got
	}
	var out bytes.Buffer
	if err := run([]string{"-json", filepath.Join(dir, "example.go")}, &out); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), `"File":"example.go"`) {
		t.Fatal(out.String())
	}
}

func TestCLICeilingAndPackageLabels(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "example.go"), []byte("package example\nfunc f() {}"), 0o600); err != nil {
		t.Fatal(err)
	}
	for _, test := range []struct{ power, ceiling string }{
		{"0", "Ceiling = 12 (fixed, -power 0)"},
		{"0.5", "Ceiling = 2 + (12 - 2) * (LOC / 80)^0.5"},
	} {
		var out bytes.Buffer
		if err := run([]string{"-base", "2", "-at", "12", "-loc", "80", "-power", test.power, dir}, &out); err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(out.String(), test.ceiling) || !strings.Contains(out.String(), "example (root)") {
			t.Fatal(out.String())
		}
	}
}

func TestCLIPackageLabels(t *testing.T) {
	binary := buildCLI(t)
	dir := t.TempDir()
	for path, pkg := range map[string]string{
		".": "brief", "detect": "detect", "internal/detect": "detect", "cmd/brief": "main",
	} {
		folder := filepath.Join(dir, path)
		if err := os.MkdirAll(folder, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(folder, "example.go"), []byte("package "+pkg+"\nfunc f() {}"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	output, err := exec.Command(binary, dir).CombinedOutput()
	if err != nil {
		t.Fatalf("CLI: %v\n%s", err, output)
	}
	out := string(output)
	for _, label := range []string{"brief (root)", "detect", "internal/detect", "main (cmd/brief)"} {
		if !strings.Contains(out, "  "+label+"\n") {
			t.Errorf("missing package label %q in:\n%s", label, out)
		}
	}
	if strings.Contains(out, "detect (detect)") || strings.Contains(out, "detect (internal/detect)") {
		t.Fatal(out)
	}
	output, err = exec.Command(binary, "-json", dir).CombinedOutput()
	if err != nil {
		t.Fatalf("JSON CLI: %v\n%s", err, output)
	}
	var data measurements
	if err := json.Unmarshal(output, &data); err != nil {
		t.Fatal(err)
	}
	var packages []string
	for _, p := range data.Packages {
		packages = append(packages, p.Name)
	}
	want := []string{".:brief", "cmd/brief:main", "detect:detect", "internal/detect:detect"}
	if !reflect.DeepEqual(packages, want) {
		t.Fatalf("packages = %q, want %q", packages, want)
	}
}
